export const actionTypes = {
    ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
    REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
    CLEAR_PRODUCT_FROM_CART: "CLEAR_PRODUCT_FROM_CART",
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    RESTORE_TOKEN: "RESTORE_TOKEN"
};